### ISSUE TITLE
Full example setup in READ.ME ? 

### ISSUE THREAD

**Issue by Antexa** [mundschenk-at/ha-valetudo-blueprints#1]
Could it be possible to add a full example in the READ.ME of each scripts ? 

For example this one didn't fit with the actual READ.ME. 
The MQTT part seems spicy to understand : "taking an MQTT topic and payload as parameters"

<img width="714" alt="image" src="https://user-images.githubusercontent.com/8592053/184906541-5a6503b7-4b4b-4827-a5a6-fed93b8eed28.png">

<img width="1081" alt="image" src="https://user-images.githubusercontent.com/8592053/184906203-329303c0-13a4-45fa-972a-22928f269923.png">

**Comment by mundschenk-at** [comment]
The script blueprints depend on each other. You have to create a "send vacuum command" script specifically for your robot and give the script entity here. If you use my blueprint to create the script, it will work out of the box. If not, you can of course create your own script if it follows the same parameter convention.

**Comment by Antexa** [comment]
Ok I get it now.

The script section is just for the setup, we need to use the script call (from the developper tab) to get it to work.

**Comment by mundschenk-at** [comment]
> Ok I get it now.
> 
> The script section is just for the setup, we need to use the script call (from the developper tab) to get it to work.

Yeah sorry I assumed that was clear: Scripts need to be called, either from another script, an automation or manually using the Developer Tools in HA. You can call them directly from the Scripts page, but that only works if all parameters have useful default values. I might add "all rooms" as the default for the Clean Rooms script though.
