### ISSUE TITLE
Clean Rooms: logbook entries but robot doesn't mind

### ISSUE THREAD

**Issue by t3kmor** [mundschenk-at/ha-valetudo-blueprints#4]
Thank you for these blueprints, they are very useful.

Unfortunately I can't get the Clean Rooms script to work.

I'll try to detail the steps I took.

------------------

### Valetudo MQTT Connectivity settings
This is what my MQTT settings look like in Valetudo.

![image](https://user-images.githubusercontent.com/121339563/211192826-6761ea3f-40ad-4931-9ad3-d4ef5a5ddc5d.png)

### Send Vacuum Command
So I put these parameters in the script Send Vacuum Command.

![image](https://user-images.githubusercontent.com/121339563/211193263-5714f851-56be-44db-9a61-9a5d3aab761f.png)

### Clean Rooms
And finally like this in the Clean Rooms script.
![image](https://user-images.githubusercontent.com/121339563/211192860-1257bd8a-24ac-4f38-8b20-b3cb4cefd4f5.png)

### Map Segments

To get the list of rooms, I went to the attributes of the Map Segments entity.

![image](https://user-images.githubusercontent.com/121339563/211192915-63d3751d-d9a3-47d9-a0cf-3b25ac16914c.png)

### Developer tools
From the developer tools, I chose the script, set the rooms list and left the other settings as they were. Then I call the script.

![image](https://user-images.githubusercontent.com/121339563/211192933-219c4517-e765-47bc-8715-00bb06ff4bfa.png)

### Logbook

After calling the script, the robot does not seem to react but I have these entries in the logbook.

![image](https://user-images.githubusercontent.com/121339563/211192970-518ab0e3-db91-4283-8f04-f51237e55e14.png)

----

What did I miss?

**Comment by mundschenk-at** [comment]
Looks good to me. What do the script traces say?

**Comment by t3kmor** [comment]
Here the Clean Rooms script traces :

![image](https://user-images.githubusercontent.com/121339563/211196289-3306d0de-64da-4537-a365-fc0df26797f8.png)

**Comment by mundschenk-at** [comment]
Looks fine. Let's have a look at the call to `scripts.valetudo_send_vacuum_command_2` (at the config and also at the `Trace Timeline`).

**Comment by t3kmor** [comment]
Config : 
![image](https://user-images.githubusercontent.com/121339563/211196604-01a2d46c-e597-493f-9a0b-39abe302ec37.png)

Trace Timeline : 
![image](https://user-images.githubusercontent.com/121339563/211196625-3e8d6fad-e4fa-4254-9501-d93df15b8542.png)

**Comment by mundschenk-at** [comment]
Sorry, I meant the `Step Details` (there's only one step anyway) and the `Changed Variables`.

**Comment by t3kmor** [comment]
I had a doubt when I did it but I'm a newbie

![image](https://user-images.githubusercontent.com/121339563/211197133-d05c1c2b-770d-40db-b1fb-347ae859e740.png)

**Comment by mundschenk-at** [comment]
The robot prefix appears all lowercase here (but was mixed-case in your initial screenshot). The `_2` suffix indicates that you probably have set up two scripts for sending the vacuum command, maybe you selected the wrong entity in the `Clean Rooms` blueprint?

**Comment by t3kmor** [comment]
OK I think I've got it.

I tried to publish the topic `MapSegmentationCapability/clean/set` with MQTT Explorer. The robot started correctly.
And now the script works. 

![image](https://user-images.githubusercontent.com/121339563/211197750-044c0802-89ac-4d99-b9c2-cf8f134ad8d9.png)


Is it possible that the "function" (sorry, I'm a novice in this domain) could have been deleted (due to a previous handling error, for example)?
And so when the script is called, it doesn't find the topic and nothing happens.

I'm not sure what I'm saying, but I think it's not from your work.

**Comment by mundschenk-at** [comment]
The problem is that your initial script sent `valetudo/dreamed9/SegmentationCapability/clean/set` when it should have sent `valetudo/DreameD9/SegmentationCapability/clean/set`. Most likely, this is because you have accidentally created two scripts called `Valetudo: Send Vacuum Command` (with the corresponding entities `script.valetudo_send_vacuum_command` and `script.valetudo_send_vacuum_command_2`). In creating the `Valetudo: Clean Rooms` script, you selected the second `script.valetudo_send_vacuum_command_2` which has an incorrect `Robot` parameter set (`dreamed9` instead of `DreameD9`).

**Comment by t3kmor** [comment]
I've finally succeeded to remove the old scripts. They were no longer appearing in the UI, which was confusing for me. 

I only have one version of each script now and everything works fine. 

Thank you very much for your help.

**Comment by mundschenk-at** [comment]
Great :)
